### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by Tamriel** [scalawarrior/scalajs-ace#12]
`libraryDependencies += "com.scalawarrior" %%% "scalajs-ace" % "0.0.4"` cannot be resolved, since it does not exist: http://amateras.osdn.jp/mvn/com/scalawarrior/scalajs-ace_sjs0.6_2.11/
`libraryDependencies += "com.scalawarrior" %%% "scalajs-ace" % "0.0.3"` does work.
Please update that repo :-)

**Comment by takezoe** [comment]
Published: http://amateras.osdn.jp/mvn/com/scalawarrior/scalajs-ace_sjs0.6_2.11/0.0.4/
