### ISSUE TITLE
setOptions method

### ISSUE THREAD

**Issue by DwarfNumber2** [scalawarrior/scalajs-ace#3]
I'm trying to turn autocomplete on from scalajs and there is a problem: 
I need setOptions method in Editor object, but couldn't find it. 
So I've tried this variant: 
val obj = jQuery.parseJSON("\"{\"enableBasicAutocompletion\":true,\"enableLiveAutocompletion\":false}\"")
editor.execCommand("setOptions", obj)

But still have no effects on my editor

**Comment by qingwei91** [comment]
PR https://github.com/scalawarrior/scalajs-ace/pull/8
