### ISSUE TITLE
fork

### ISSUE THREAD

**Issue by MasseGuillaume** [scalawarrior/scalajs-ace#7]
Hi guys,

I forked you repo here: https://github.com/MasseGuillaume/AcePlayground/blob/master/ace/src/main/scala/com.scalawarrior.scalajs.ace/Ace.scala

There is no license, I hope it's ok with you.

I made some modifications and I can contribute them back to this repo with git subtree.

I dont know what's your sbt setup but it look like I'm having trouble with ace require. How do you access for example https://github.com/scalawarrior/scalajs-ace/blob/master/src/main/scala/com/scalawarrior/scalajs/ace/Ace.scala#L57

given ace is using define/require
https://github.com/ajaxorg/ace-builds/blob/master/src/ext-keybinding_menu.js#L1

maybe you are using an older version ?

``` scala
@ScalaJSDefined
trait LineWidget extends js.Object {
  val row: Int
  val html: String
}

object LineWidgets {
  def apply(session: IEditSession): LineWidgets = {
    val LineWidgets = global.require("ace/line_widgets").LineWidgets
    js.Dynamic.newInstance(LineWidgets)(session).asInstanceOf[LineWidgets]
  }
}

@js.native
class LineWidgets extends js.Object {
  def attach(editor: Editor): Unit = js.native
  def dettach(editor: Editor): Unit = js.native
  def addLineWidget(widget: LineWidget): LineWidget = js.native
  def removeLineWidget(widget: LineWidget): Unit = js.native
}
```

**Comment by takezoe** [comment]
> There is no license, I hope it's ok with you.

Sorry, I will add a license file. It would be ASL2.0.

> I made some modifications and I can contribute them back to this repo with git subtree.

Great! I'm looking forward to your contribution.

> I dont know what's your sbt setup but it look like I'm having trouble with ace require. 

I will check soon and reply in this issue.

**Comment by MasseGuillaume** [comment]
hey @takezoe, sorry for the trouble but I think I will go with Codemirror. I was trying out LineWidget from ace and found it a bit buggy. Also there is no sublime text key binding :P.

I think there is still idea you can incorporate into this facade:
- packaging ace javascript: https://github.com/MasseGuillaume/AcePlayground/blob/master/build.sbt#L44-L47
- require bug/solution above

**Comment by takezoe** [comment]
@MasseGuillaume Oh, that's regrettable...

> I think there is still idea you can incorporate into this facade:

Yes. I will consider about them :-)
